[package]
name = "visualiser"
authors = ["Aleksandr Tikka <altikka@student.hive.fi>"]
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gio = "0.15.12"
gtk = "0.15.5"
